All code in one cell

In [ ]:
import pandas as pd 
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

df = pd.read_excel("http://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx")
df.head()
df['Description'] = df['Description'].str.strip()
df.dropna(axis=0, subset=['InvoiceNo'], inplace=True)
df['InvoiceNo'] = df['InvoiceNo'].astype('str')
df = df[~df['InvoiceNo'].str.contains('C')]
df.head()
basket = (df[df['Country'] == "France"]
        .groupby(['InvoiceNo', 'Description'])['Quantity']
        .sum().unstack().reset_index().fillna(0)
        .set_index('InvoiceNo'))
basket.head()
def encoding_units(x):
  if x <= 0:
    return 0
  if x > 0:
    return 1

basket_sets = basket.applymap(encoding_units)
basket_sets.drop('POSTAGE', inplace=True, axis=1)
basket_sets.head()
frequen_itemsets = apriori(basket_sets, min_support=0.07, use_colnames=True)
frequen_itemsets.head()
rules = association_rules(frequen_itemsets, metric="lift", min_threshold=1)
rules.head()
rules[ (rules['lift'] >= 6) &
       (rules['confidence'] >= 0.8) ]
rules.head(10)

                       antecedents  ... conviction
0      (ALARM CLOCK BAKELIKE PINK)  ...   3.283859
1     (ALARM CLOCK BAKELIKE GREEN)  ...   3.791383
2       (ALARM CLOCK BAKELIKE RED)  ...   5.568878
3     (ALARM CLOCK BAKELIKE GREEN)  ...   4.916181
4      (ALARM CLOCK BAKELIKE PINK)  ...   3.293135
5       (ALARM CLOCK BAKELIKE RED)  ...   4.153061
6           (DOLLY GIRL LUNCH BOX)  ...   3.102273
7             (SPACEBOY LUNCH BOX)  ...   2.101190
8       (PLASTERS IN TIN SPACEBOY)  ...   2.363588
9  (PLASTERS IN TIN CIRCUS PARADE)  ...   1.835747

[10 rows x 9 columns]

Real code

In [ ]:
import pandas as pd 
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

df = pd.read_excel("OnlineRetail.csv")
df.head()

  InvoiceNo StockCode  ... CustomerID         Country
0    536365    85123A  ...    17850.0  United Kingdom
1    536365     71053  ...    17850.0  United Kingdom
2    536365    84406B  ...    17850.0  United Kingdom
3    536365    84029G  ...    17850.0  United Kingdom
4    536365    84029E  ...    17850.0  United Kingdom

[5 rows x 8 columns]

In [ ]:
df['Description'] = df['Description'].str.strip()
df.dropna(axis=0, subset=['InvoiceNo'], inplace=True)
df['InvoiceNo'] = df['InvoiceNo'].astype('str')
df = df[~df['InvoiceNo'].str.contains('C')]
df.head()

  InvoiceNo StockCode  ... CustomerID         Country
0    536365    85123A  ...    17850.0  United Kingdom
1    536365     71053  ...    17850.0  United Kingdom
2    536365    84406B  ...    17850.0  United Kingdom
3    536365    84029G  ...    17850.0  United Kingdom
4    536365    84029E  ...    17850.0  United Kingdom

[5 rows x 8 columns]

In [ ]:
basket = (df[df['Country'] == "France"]
        .groupby(['InvoiceNo', 'Description'])['Quantity']
        .sum().unstack().reset_index().fillna(0)
        .set_index('InvoiceNo'))
basket.head()

Description  10 COLOUR SPACEBOY PEN  ...  ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo                            ...
536370                          0.0  ...                              0.0
536852                          0.0  ...                              0.0
536974                          0.0  ...                              0.0
537065                          0.0  ...                              0.0
537463                          0.0  ...                              0.0

[5 rows x 1563 columns]

In [ ]:
def encoding_units(x):
  if x <= 0:
    return 0
  if x > 0:
    return 1

basket_sets = basket.applymap(encoding_units)
basket_sets.drop('POSTAGE', inplace=True, axis=1)
basket_sets.head()

Description  10 COLOUR SPACEBOY PEN  ...  ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo                            ...
536370                            0  ...                                0
536852                            0  ...                                0
536974                            0  ...                                0
537065                            0  ...                                0
537463                            0  ...                                0

[5 rows x 1562 columns]

**TRAINING DATA**

In [ ]:
frequen_itemsets = apriori(basket_sets, min_support=0.07, use_colnames=True)
frequen_itemsets.head()

    support                        itemsets
0  0.071429   (4 TRADITIONAL SPINNING TOPS)
1  0.096939    (ALARM CLOCK BAKELIKE GREEN)
2  0.102041     (ALARM CLOCK BAKELIKE PINK)
3  0.094388      (ALARM CLOCK BAKELIKE RED)
4  0.081633  (BAKING SET 9 PIECE RETROSPOT)

In [ ]:
rules = association_rules(frequen_itemsets, metric="lift", min_threshold=1)
rules.head()

                    antecedents  ... conviction
0   (ALARM CLOCK BAKELIKE PINK)  ...   3.283859
1  (ALARM CLOCK BAKELIKE GREEN)  ...   3.791383
2  (ALARM CLOCK BAKELIKE GREEN)  ...   4.916181
3    (ALARM CLOCK BAKELIKE RED)  ...   5.568878
4   (ALARM CLOCK BAKELIKE PINK)  ...   3.293135

[5 rows x 9 columns]

In [ ]:
rules[ (rules['lift'] >= 6) &
       (rules['confidence'] >= 0.8) ]
rules.head()

                    antecedents  ... conviction
0   (ALARM CLOCK BAKELIKE PINK)  ...   3.283859
1  (ALARM CLOCK BAKELIKE GREEN)  ...   3.791383
2  (ALARM CLOCK BAKELIKE GREEN)  ...   4.916181
3    (ALARM CLOCK BAKELIKE RED)  ...   5.568878
4   (ALARM CLOCK BAKELIKE PINK)  ...   3.293135

[5 rows x 9 columns]

In [ ]:
basket['ALARM CLOCK BAKELIKE GREEN'].sum()

340.0

In [ ]:
basket['ALARM CLOCK BAKELIKE RED'].sum()

316.0

In [ ]:
basket2 = (df[df['Country'] =="Germany"]
          .groupby(['InvoiceNo', 'Description'])['Quantity']
          .sum().unstack().reset_index().fillna(0)
          .set_index('InvoiceNo'))

basket_sets2 = basket2.applymap(encoding_units)
basket_sets2.drop('POSTAGE', inplace=True, axis=1)
frequent_itemsets2 = apriori(basket_sets2, min_support=0.05, use_colnames=True)
rules2 = association_rules(frequent_itemsets2, metric="lift", min_threshold=1)

rules2[ (rules2['lift'] >= 4) &
        (rules2['confidence'] >= 0.5)]

                        antecedents  ... conviction
1   (PLASTERS IN TIN CIRCUS PARADE)  ...   2.076984
7        (PLASTERS IN TIN SPACEBOY)  ...   2.011670
10    (RED RETROSPOT CHARLOTTE BAG)  ...   5.587746

[3 rows x 9 columns]